table Dim_StoreFormat
	lineageTag: 1584cc67-747a-44d6-8d8f-eb0a8b7a60bf

	column StoreFormatID
		dataType: int64
		formatString: 0
		lineageTag: ced9d71c-1279-4951-8074-a6cbe9cf865f
		summarizeBy: none
		sourceColumn: StoreFormatID

		annotation SummarizationSetBy = Automatic

	column StoreFormat
		dataType: string
		lineageTag: 77254cbc-c635-4edc-a761-152b05c901e0
		summarizeBy: none
		sourceColumn: StoreFormat

		annotation SummarizationSetBy = Automatic

	partition Dim_StoreFormat = m
		mode: import
		source =
				let
				    Source = Raw_Sales,
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"store_format"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "StoreFormatID"}, {"store_format", "StoreFormat"}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Renamed Columns",{"StoreFormatID", "StoreFormat"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

